import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, Award, BookOpen, Clock } from 'lucide-react';

interface QAItem {
  q: string;
  a: string;
  category: string;
}

export const InterviewMode: React.FC = () => {
  const [activePitchTab, setActivePitchTab] = useState<'30s' | '2min' | '5min'>('30s');
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs: QAItem[] = [
    {
      q: 'Why SQS?',
      a: 'SQS acts as an asynchronous message queue buffer that decouples job API producers from worker consumers. It prevents traffic spikes from overloading downstream databases and enables horizontal worker scaling.',
      category: 'Architecture',
    },
    {
      q: 'Why Lambda?',
      a: 'AWS Lambda provides stateless, event-driven serverless compute. Invocations scale automatically based on SQS queue depth from 0 to 1,000+ parallel instances with zero idle server cost.',
      category: 'Compute',
    },
    {
      q: 'Why not EC2?',
      a: 'EC2 requires provisioning, OS patching, auto-scaling policy tuning, and continuous payment even when idle. Lambda eliminates operational overhead for event-driven bursty batch workloads.',
      category: 'Compute',
    },
    {
      q: 'Why DynamoDB?',
      a: 'DynamoDB is a fully managed NoSQL key-value database designed for single-digit millisecond reads and writes. On-demand billing handles burst write traffic generated by parallel Lambda workers without schema migrations.',
      category: 'Database',
    },
    {
      q: 'Why caching?',
      a: 'Caching stores frequently requested job state records in high-speed Redis memory. It reduces DynamoDB read capacity units (RCU), cuts read latency from ~20ms to ~2ms, and prevents database read hotspots.',
      category: 'Caching',
    },
    {
      q: 'What is a cache hit?',
      a: 'A cache hit occurs when requested data is found in Redis memory, returning the result immediately without executing a database read query.',
      category: 'Caching',
    },
    {
      q: 'What is TTL?',
      a: 'Time-To-Live (TTL) is an automatic expiration timestamp attached to cached Redis items (`CACHE_TTL_SECONDS=60`). Once expired, stale items are evicted to ensure data freshness.',
      category: 'Caching',
    },
    {
      q: 'What happens when Lambda fails?',
      a: 'If a Lambda worker throws an unhandled exception or times out, the SQS message is not deleted. After the visibility timeout (30s) expires, SQS makes the message visible again for another worker to retry.',
      category: 'Resilience',
    },
    {
      q: 'What happens with duplicate SQS messages?',
      a: 'SQS Standard queues guarantee at-least-once delivery, meaning duplicate messages can occur. The worker uses the unique `jobId` as an idempotency key to drop duplicate executions.',
      category: 'Resilience',
    },
    {
      q: 'What is idempotency?',
      a: 'Idempotency ensures that executing an operation multiple times produces the exact same final system state as executing it once.',
      category: 'Resilience',
    },
    {
      q: 'What is a DLQ?',
      a: 'A Dead Letter Queue (DLQ) isolates messages that fail repeatedly (exceeding `maxReceiveCount=3`). It prevents poisonous messages from looping infinitely and blocking the queue.',
      category: 'Resilience',
    },
    {
      q: 'What is Lambda concurrency?',
      a: 'Lambda concurrency measures the number of function instances actively processing events simultaneously. Reserved concurrency caps instances to protect downstream systems.',
      category: 'Compute',
    },
    {
      q: 'Why is parallel processing faster?',
      a: 'Parallel processing breaks a batch into N independent jobs and processes them concurrently across multiple workers, reducing total runtime from $O(N)$ serial time to $O(1)$ constant time.',
      category: 'Performance',
    },
    {
      q: 'When does parallel processing NOT help?',
      a: 'Parallel processing provides no benefit for strictly dependent sequential tasks (where Job B requires Job A output) or when bounded by database write bottlenecks.',
      category: 'Performance',
    },
    {
      q: 'What are the trade-offs of caching?',
      a: 'Trade-offs include eventual consistency risks, cache invalidation complexity, extra memory cost, and potential cache stampede stampedes during cold starts.',
      category: 'Caching',
    },
    {
      q: 'What happens during a cache miss?',
      a: 'During a cache miss, the system queries DynamoDB, writes the retrieved item to Redis with TTL, and returns the item to the client.',
      category: 'Caching',
    },
    {
      q: 'How would you migrate this architecture with minimal downtime?',
      a: 'Using a 4-phase weighted traffic shift: Dual Writes → Canary Parallel Validation → Route 53 Weighted DNS Shift (20% → 100%) → Decommissioning legacy serial monolith.',
      category: 'Migration',
    },
    {
      q: 'Is this lift-and-shift, re-platforming, or re-architecting?',
      a: 'This is a **Re-architecting** pattern. We refactored synchronous monolithic serial execution into decoupled, event-driven serverless micro-components (API Gateway + SQS + Lambda + DynamoDB + Redis).',
      category: 'Architecture',
    },
  ];

  return (
    <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-xs space-y-8">
      <div>
        <h2 className="text-lg font-semibold text-slate-900 flex items-center space-x-2">
          <Award className="h-5 w-5 text-indigo-600" />
          <span>Interview Mode & System Design Defense Guide</span>
        </h2>
        <p className="text-xs text-slate-500 mt-1">
          Concise explanations, architectural pitches, and technical answers based on the actual platform codebase.
        </p>
      </div>

      {/* Elevator Pitches Tabs */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-200 pb-3">
          <span className="text-xs font-bold text-slate-800 flex items-center space-x-1.5">
            <Clock className="h-4 w-4 text-sky-600" />
            <span>Elevator Pitches</span>
          </span>
          <div className="flex bg-slate-200/80 p-1 rounded-lg">
            {(['30s', '2min', '5min'] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActivePitchTab(tab)}
                className={`px-3 py-1 rounded-md text-xs font-semibold transition-all ${
                  activePitchTab === tab ? 'bg-white text-sky-700 shadow-xs' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                {tab === '30s' ? '30-Sec Summary' : tab === '2min' ? '2-Min Overview' : '5-Min Architecture'}
              </button>
            ))}
          </div>
        </div>

        <div className="text-xs text-slate-700 leading-relaxed font-sans">
          {activePitchTab === '30s' && (
            <p>
              "I built an <strong>AWS Event-Driven Performance Optimization Platform</strong> that demonstrates how serial batch processing bottlenecks can be eliminated. By replacing a synchronous loop with an <strong>Amazon SQS queue</strong> and <strong>parallel AWS Lambda workers</strong> backed by <strong>Redis TTL caching</strong> and <strong>DynamoDB</strong>, we achieved an <strong>88%+ reduction in latency</strong> and scaled throughput from 5 to 50+ jobs/sec."
            </p>
          )}

          {activePitchTab === '2min' && (
            <p>
              "In standard monolithic applications, processing 20 batch jobs sequentially takes several seconds because total runtime scales linearly as $O(N)$. I re-architected this into a cloud-native event-driven system. Clients submit job batches to an <strong>API Gateway REST endpoint</strong>, which enqueues messages into <strong>Amazon SQS</strong>. SQS fans out messages across a pool of <strong>stateless AWS Lambda workers</strong> executing concurrently in $O(1)$ constant time. Workers persist results to <strong>DynamoDB</strong> and enforce <strong>idempotency via unique job IDs</strong>. For frequent read queries, a <strong>Redis in-memory cache</strong> reduces database reads by over 80% with sub-2ms response times."
            </p>
          )}

          {activePitchTab === '5min' && (
            <div className="space-y-2">
              <p>
                "This platform compares three distinct processing paradigms: <strong>Serial</strong>, <strong>Parallel SQS + Lambda</strong>, and <strong>Parallel + Redis Caching</strong>.
              </p>
              <p>
                <strong>1. Ingestion & Queuing:</strong> API Gateway receives batch requests and invokes a producer Lambda that publishes messages in batch mode to SQS. SQS flattens traffic spikes and acts as a resilient buffer.
              </p>
              <p>
                <strong>2. Worker Execution & Idempotency:</strong> Lambda worker functions scale horizontally based on queue depth. To handle SQS at-least-once delivery, workers check an in-memory idempotency set before updating DynamoDB.
              </p>
              <p>
                <strong>3. Fault Tolerance & Resilience:</strong> Failed worker executions trigger SQS visibility timeout expiration and retries up to 3 times before routing unprocessable messages to a Dead Letter Queue (DLQ).
              </p>
              <p>
                <strong>4. Caching & Observability:</strong> Read requests hit a Redis cache layer with 60s TTL, cutting DynamoDB RCU costs while CloudWatch aggregates concurrency telemetry."
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Interactive Candidate FAQ Accordion */}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold text-slate-900 flex items-center space-x-2">
          <BookOpen className="h-4 w-4 text-indigo-600" />
          <span>Likely Interview Questions & Answers</span>
        </h3>

        <div className="divide-y divide-slate-100 border border-slate-200 rounded-xl overflow-hidden">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div key={faq.q} className="bg-white">
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-slate-50 transition-colors"
                >
                  <div className="flex items-center space-x-3">
                    <span className="text-[10px] font-mono font-bold bg-slate-100 text-slate-600 px-2 py-0.5 rounded">
                      {faq.category}
                    </span>
                    <span className="text-xs font-semibold text-slate-900">{faq.q}</span>
                  </div>
                  <ChevronDown className={`h-4 w-4 text-slate-400 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
                </button>

                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="px-4 pb-4 text-xs text-slate-600 bg-slate-50/50 leading-relaxed font-sans border-t border-slate-100 pt-2"
                    >
                      {faq.a}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
